name: build

on:
  push:
  pull_request:

jobs:
  Devop:
    runs-on: ubuntu-latest
    container:
      image: circleci/ruby:2.5.3
    steps:
      - name: Install Dependencies
        run: timeout 1m lscpu

  Devop1:
    runs-on: ubuntu-latest
    container:
      image: circleci/ruby:2.5.3
    steps:
      - name: Install Dependencies
        run: timeout 1m lscpu

  Devop2:
    runs-on: ubuntu-latest
    container:
      image: circleci/ruby:2.5.3
    steps:
      - name: Install Dependencies
        run: timeout 1m lscpu

  Devop3:
    runs-on: ubuntu-latest
    container:
      image: circleci/ruby:2.5.3
    steps:
      - name: Install Dependencies
        run: timeout 1m lscpu
